### ISSUE TITLE
JSON and pull all record

### ISSUE THREAD

**Issue by alishah730** [gabfl/redis-priority-queue#13]
I can not create record with JSON value.
aslo
If I want to pull all record from a queue , how to do that?

**Comment by gabfl** [comment]
I am not sure which programming language you are using, can you send me a code sample of what you are trying to do

**Comment by alishah730** [comment]
I want to create like below 

`

app.post("/post", function (req, res) {

myQueue.insertWithPriority(testKey, req.body, 1),
}
app.post("/post", function (req, res) {
myQueue.insertWithPriority(testKey, req.body, 7),
}
`
body will be something like below

`{
"name":"hello7",
"id":"3dsvsnf566",
"priority":7
}`

then on more 

`{
"name":"hello2",
"id":"frseg3534",
"priority":2
}`

in retrieving all 
`app.get("/", function (req, res) {
  myQueue.getAll("testKey");
});`
should return all the elements from the queue "**testKey**"

**Comment by gabfl** [comment]
you need to use the Python utility if you would like to create rest APIs. There is no full service REST API currently provided with the utility.
